#!/bin/bash
#	USAGE: make-help G4BL_DIR SOURCE_DIR
#
#	G4BL_DIR is used to run g4bl. SOURCE_DIR is used to find the
#	source files, and to write share/g4beamline/Help.html.
#
#	NOTE: This script creates Help.html in SOURCE_DIR. That's
#	because it is run only on Mac OS X (Darwin), and the other
#	OS builds assume Help.html already exists. So G4beamline
#	distributions must be built first on a Mac (happens 
#	naturally).
#
#	This script first copies G4blGuiInstructions.html into
#	Help.html. It then runs g4bl to get a list of commands,
#	and runs g4bl again to get a list of particles. It then 
#	ends the HTML file.
#
#	G4BLVERSION is obtained from SOURCE_DIR/CMakeLists.txt

echo "make-help '$1' '$2'"

G4BL_DIR="$1"
'cd' "$2"

set -e 

if ! test -r share/g4beamline/G4blGuiInstructions.html
then
	echo "make-help: wrong directory"
	exit 1
fi

if test -z "$G4BL_DIR"
then
	echo "make-help: G4BL_DIR not set"
	exit 1
fi

G4BLVERSION=$(grep '^set(G4BLVERSION' CMakeLists.txt | \
						sed -e 's/.* //' -e 's/).*//')

INPUTFILE=/tmp/in.$$

trap "rm -f $INPUTFILE" 0

OUT=share/g4beamline/Help.html
rm -f $OUT
sed "s/VERSION/$G4BLVERSION/" <share/g4beamline/G4blGuiInstructions.html >$OUT

echo "<A name=Commands></A>" >>$OUT
echo "<h2>G4beamline Commands</h2>" >>$OUT
echo "<pre>" >>$OUT
cat <<-! >$INPUTFILE
	*
	*
	*
	list commands
	*
	*
	*
	help -exit *
!
$G4BL_DIR/bin/g4bl $INPUTFILE 2>&- | \
    sed -e '1,/^----/d' -e 's/&/\&amp;/g' -e 's/>/\&gt;/g' -e 's/</\&lt;/g' \
    >>$OUT
echo "</pre>" >>$OUT

echo "<A name=Particles>" >>$OUT
echo "<h2>List of Particles (QGSP_BERT)</h2>" >>$OUT
echo "<pre>" >>$OUT
cat <<-! >$INPUTFILE
	physics QGSP_BERT
	*
	*
	*
	list -exit particles
!
$G4BL_DIR/bin/g4bl $INPUTFILE 2>&- | \
    sed -e '1,/^----/d' -e 's/&/\&amp;/g' -e 's/>/\&gt;/g' -e 's/</\&lt;/g' \
    >>$OUT
echo "</pre>" >>$OUT

echo "</body></html>" >>$OUT
